--계정생성
CREATE USER c##surfer IDENTIFIED BY 1234
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    PROFILE DEFAULT;
--권한부여
GRANT CONNECT, RESOURCE TO c##surfer;
GRANT CREATE VIEW, CREATE SYNONYM TO c##surfer;
GRANT UNLIMITED TABLESPACE TO c##surfer;
--락 풀기
ALTER USER c##surfer ACCOUNT UNLOCK;