insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 낙화 핑크 콜드컵 710ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 풀 블라썸 콜드컵 591ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 핑크 여행 파우치',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'딸기 컬러체인징 리유저블 콜드컵 709ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'말차 컬러체인징 리유저블 컵 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'21 허쉘 그린 백팩',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'21 허쉘 그린 에코백',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'21 허쉘 그린 파우치',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'21 SS 오드리 올리브 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'21 SS 커뮤터 올리브 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'21 SS 폴리 올리브 워터보틀 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'21 SS 허쉘 미르 커피체리 텀블러 591ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'21 SS 허쉘 블랙 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'21 SS 허쉘 커피체리 데스크 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 무궁화 글라스 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 글라스 서버 710ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 라탄 피크닉 캐리어',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 리유저블 컵 세트(4개입) 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 스탠리 클래식 보온병 710ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 스트라이프 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 아이코닉 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 JOE 보온병 480ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 JOK 보온병 500ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 SS 나수 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 SS 모카 텀블러 444ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 SS 정글 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 SS 찰리 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 SS 찰리즈 머그 414ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 스프링 SS 하비 콜드컵 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리 블루밍 블루글라스 세라믹소서 237ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리 블루밍 핑크글라스 세라믹소서 237ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 골드글리터 핸들글라스 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 글라스 카라페 앤 머들러739ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 꽃봉오리 세라믹 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 라벤더 수변 3단 우산',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 블루밍 레나 워터보틀 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 블루밍 블루 핸들 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 블루밍 핑크글라스 티팟 500ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 세라믹 티 컵 세트 (2P)',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 아치 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 우드 돔 플레이트',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 컬러체인징 콜드컵 세트 709ml(2P)',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 판타지 머들러',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 판타지 손거울 세트',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 판타지 아크릴 코스터',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 판타지 트레이',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 퍼플빔 스터드 콜드컵 710ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 플라워 베어리스타 키 체인',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 플라워 핸들 글라스 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 플로런스 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 핑크 스트라이프 보냉백',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 핑크 피크닉 매트',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 핑크빔 스터드 콜드컵 710ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 화이트 머그 296ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 FFM 보온병 520ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 FHL 스트로 보온병 400ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 체리블라썸 ROB 핑크 보온병 1200ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 KSNY 스퀘어 스트로우베리 WB 414ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 KSNY 스트로우베리 러기지 택',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 SS 모카 KSNY 아이콘 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 SS 무궁화 트로이 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 SS 엘마 KSNY 아이콘 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'22 SS MiiR KSNY 데스크탑 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린 그러데이션 사이렌 콜드컵 591ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린 리유저블 콜드컵 709ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린 사이렌 도트 머그 237ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린 사이렌 도트 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린 사이렌 슬리브 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린 사이렌 클래식 머그 237ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린 사이렌 클래식 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린 사이렌 클래식 머그 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린 워드마크 폼 콜드컵 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린 팝핸들 콜드컵 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린스토리 리사이클드 에코백',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린스토리 리유저블 컵 473ml (3p)',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린스토리 리유저블 콜드컵 709ml (3p)',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'그린스토리 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'대한항공 Buckle-Up 카드',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'더양평 DTR 대시보드 피규어 키체인',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'더양평 DTR 스탠리 quencher 텀블러 591ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'더양평 DTR 주차알림판 키체인',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'더양평 DTR SS 캠핑 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'더양평DTR 스타벅스 카드',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'러브 인 패리스 스퀘어 워터보틀 414ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'러브 인 패리스 핑크 머그 296ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'러브 인 패리스 화이트 머그 296ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'러브인패리스 폴더블 에코백',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'레드 리유저블 컵 세트',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'민트 리유저블 컵 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'민트 사각 푸드 박스 1000ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'민트 사이렌 워터보틀 532ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'민트 원형 푸드 박스 850ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'밀리타 종이 필터 #2',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'밀리타 종이 필터 #4',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'버디 미니 파우치',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'별다방 스퀘어 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'별다방 아트월 퍼즐(500PCS)',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'부산 투어 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'부산 투어 미니백',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'북청사자놀음 데미머그 89ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'북청사자놀음 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'브라운 사이렌 글라스 자 946ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'브라운 사이렌 커피 프레스 450ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'블랙 링 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'블랙 앤 골드 머그 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'빈 데어 코리아 에코백',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'사이렌 글라스 컨테이너',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'사이렌 레버 드리퍼',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'사이렌 커피 체리 콜드컵 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'서울 제주 데미머그 세트',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'서울 투어 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'서울 투어 에코백',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'스탠리 그린 박스',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'스탠리 블루 워터 저그 3.8L',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'스튜던트 가죽 펜슬 케이스',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'스프링가든 스푼 세트',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'스프링가든 패브릭 코스터',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'스프링가든 피크닉 런치박스',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'실버 사이렌 뱃지 글라스 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'어뮤즈먼트 파크 스타 키체인',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'커피리프 슬리브 워터보틀 414ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'코리아 데미머그 세트(4개입)',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'크림 리드 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'크림 컴프레소',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 그린 리드 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 더블월 글라스 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 루비 레드 티 팟 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 민트 블렌드 12개입',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 블루 글라스 콜드컵 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 얼 그레이 12개입',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 유스베리 12개입',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 잉글리쉬 브렉퍼스트 12개입',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 제주녹차(15개입)',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 캐모마일 12개입',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 펠트 그린 티 팟 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 포터 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 핑크 글라스 콜드컵 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 핑크 리드 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'티바나 히비스커스 12개입',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'파리지앵 베레모 머그 296ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'파리지앵 베어리스타',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'패밀리 가방 세트',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'패밀리 볼 세트',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'플라워가든 사이렌 고블렛 글라스 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'플라워가든 옐로우 핸들 글라스 237ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'플라워가든 클레이 워터보틀 591ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'플라워가든 투고 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'플라워가든 JNO 보온병 500ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'한복 베어리스타 걸',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'한복 베어리스타 보이',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'해운대 엑스더스카이 머그 340ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'해운대 엑스더스카이 머들러',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'화이트 사이렌 그라인더',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'화이트 사이렌 커피 클립 스쿱',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'환구단 스퀘어 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'JDN 크림 투고컵 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'JMZ 그린 사이렌 보온병 350ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'JNL 어뮤즈먼트 파크 보온병 500ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 스프링 뉴포트 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 꽃잎 콜드컵 532ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 라일락 핸들 머그 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 미르 클러스터 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 블루밍 뉴턴 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 셰이 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 스탠리 켄처 텀블러 591ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 아이슬란드 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 알래스카 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 처비돔 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 코나 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 트로이 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 퍼플 JDE 텀블러 600ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 핑크 사이렌 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 핑크 엘마 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 22 체리블라썸 DW 투고 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 경주 투어 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 그린 사이렌 원핸드 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 그린 사이렌 케틀 550ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 그린 스탠리 아이슬란드 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 그린 처비 핸들 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 그린스토리 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 러브 인 패리스 엘마 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 메탈릭 골드 미르 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 메탈릭 골드 콕시클 텀블러 266ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 메탈릭 그레이 미르 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 메탈릭 그레이 콕시클 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 메탈릭 실버 미르 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 메탈릭 실버 콕시클 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 미르 리저브 그레이 골드 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 미르 리저브 커피 오리진 텀블러 295ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 미르 리저브 핸들 텀블러 591ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 미르 사이렌 민트 텀블러 591ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 부산 투어 텀블러 355m',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 북청사자놀음 텀블러 473ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 블랙 데비 머그 414ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 블랙 앤 골드 스탠리 보온병 500ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 블랙 앤 골드 콜드컵 591ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 사이렌 스토퍼 콜드컵 532ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 서울 투어 텀블러 355ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 스탠리 그린 플로우 콜드컵 591ml',default);
insert into hashtag_classification values (hashtag_gmenu_id_seq.nextval,'SS 스탠리 리저브 아이슬란드 텀블러 473ml',default);

commit;